### ISSUE TITLE
python rosbag module 

### ISSUE THREAD

**Issue by bischofs** [valtech/ros_hadoop#16]
Im using your msg_map function however trying to find the python 3 rosbag module is proving difficult, I don't want to install the entire ros software on each node on the cluster and even when I do its python 2. There is a python3-rosbag package floating around but its marked unstable for debian etc. 

Where did you guys get your python rosbag from? Was it a pip install or apt?

**Comment by wiegelmann** [comment]
ROS software has to be installed on all nodes because the parsing and processing of all possible ROS messages happens on each node in parallel. Hence if there is interest, we can implement custom solutions in Scala or Python without ROS but the generic solution supporting any possible combination of ROS messages requires ROS on all nodes.

As for Python 3, we need to try again, last time didn't worked.

On the Dockerfile the image is based on the ros:kinetic where ROS is installed with the apt and official repository as documented in the ROS installation instructions. See docker hub.

**Comment by autovia-user** [comment]
[ROS Noetic](http://wiki.ros.org/noetic/Installation/Source) targets Python3 so let us close this issue.

If you still encounter issues please feel free to open an issue and leave the comments.
