### ISSUE TITLE
Any plans to add a Rosbag OutputFormat class?

### ISSUE THREAD

**Issue by adammacudzinski** [valtech/ros_hadoop#21]
Since Hadoop doesn't support random writes, how would you guys go about updating the Bag header record index_pos field? This is the main theoretical issue with implementing a Hadoop OutputFormat class for Rosbags, from what I can tell.

**Comment by wiegelmann** [comment]
First of all, thanks for your question.

We do not plan to open source a Rosbag OutputFormat class at the moment. The reason is that the overwhelming majority of use cases do not need it. 
Usually our open source InputFormat is used for analysis purposes. Large rosbag files of data being acquired on the spot on a robot file storage and simply copied into HDFS after being closed on the robot (random access) FS. The huge advantage of not converting to other formats (e.g. parquet) being that it can be used for simulation, play, etc. directly from HDFS (e.g. over open or nfs) while still having very fast parallel analytics at scale with mapreduce, spark APIs among others.

Yes, the HDFS is an immutable append only FileSystem and there is a good reason for such a design decision. However there are many (Databricks, S3, MapR, Casandra FS, etc.) random access distributed file systems that now implement HDFS interfaces and can be "mounted" as such in your pipeline. Also "native" Hadoop applications such as HBase use the internal design of HDFS but provide a random access interface. So no theoretical impediment for a Rosbag OutputFormat.

A very quick and "naive" implementation might be done even with the plain standard HDFS API, for instance by writing all blocks starting with the second up to the end including the second level index and that would be very much analogous to the native Rosbag closing operation. The first block is then updated with the offset and written separately at the end. Now one can use the native java concat HDFS FileSystem API to properly access the data (see public void concat(Path trg, Path[] psrcs) throws IOException). Advanced Parquet techniques use the same tricks together with "folder" partition ...

If you have a concrete use case for a Rosbag OutputFormat please contact us, we might be able to help.
